- .gitignore
Add .idea/caches and /codeStyles/Project.xml in .gitignore
> EDIT .GITIGNORE

- app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/LoginFragment.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/MainActivity.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Structure/AuthenticatedUser.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Structure/Guest.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Structure/User.java
To force using the builder that will SECURE the access
> ADD PROTECTED ACCESS TO CLASS GUEST AND AUTHENTICATED USER

- app/src/main/java/ch/epfl/sweng/zuluzulu/MainActivity.java
> Fix logout xD #19

- app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/ChatFragment.java
Just a little fix about the messages sender name
> The chat messages have a correct sender name

- app/src/androidTest/java/ch/epfl/sweng/zuluzulu/ChannelFragmentTest.java
- app/src/androidTest/java/ch/epfl/sweng/zuluzulu/ChatFragmentTest.java
- app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Fragments/ProfileFragmentTest.java
- app/src/androidTest/java/ch/epfl/sweng/zuluzulu/LogoutTest.java
- app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Utility.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/MainActivity.java
- app/src/main/res/layout/fragment_chat.xml
- app/src/main/res/layout/fragment_profile.xml
ADDED TESTS FOR CHAT AND BETTER PROFILE POSITION
It was already done but travis wouldn't pass. I am trying again in a fresh pull request. Tests are improved.
> Dahn profile

- app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Utility.java
Just added @deprecated to the fullLogin() functions
Now we should create the user with Utility.createAuthenticatedUser() and pass it to the fragment
> ADD DEPRECATED FUNCTIONS

- app/src/androidTest/java/ch/epfl/sweng/zuluzulu/ChannelFragmentTest.java
- app/src/androidTest/java/ch/epfl/sweng/zuluzulu/ChatFragmentTest.java
- app/src/androidTest/java/ch/epfl/sweng/zuluzulu/EventFragmentTest.java
- app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Fragments/ProfileFragmentTest.java
- app/src/androidTest/java/ch/epfl/sweng/zuluzulu/ProfileFragmentTest.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Adapters/ChatMessageAdapter.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/ChannelFragment.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/ChatFragment.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Structure/Channel.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Structure/ChatMessage.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Structure/Utils.java
- app/src/main/res/layout/channel.xml
- app/src/test/java/ch/epfl/sweng/zuluzulu/ChannelTest.java
- app/src/test/java/ch/epfl/sweng/zuluzulu/ChatMessageTest.java
Just some cleaning, nothing to worry about.
> Reformat code

- app/src/main/java/ch/epfl/sweng/zuluzulu/Structure/AssociationsUrlHandler.java
> CORRECT UNRECOGNIZE CHARACTER #77

- app/src/androidTest/java/ch/epfl/sweng/zuluzulu/LoginTest.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/MainActivity.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/tequila/AuthClient.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/tequila/AuthServer.java
- app/src/test/java/ch/epfl/sweng/zuluzulu/AuthClientTest.java
cf piazza
https://piazza.com/class/jm0kpuvsnq61l9?cid=62
> fix logout

- app/src/androidTest/java/ch/epfl/sweng/zuluzulu/LogoutTest.java
- app/src/androidTest/java/ch/epfl/sweng/zuluzulu/MainActivityAsUserTest.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/CommunicationTag.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/LoginFragment.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/WebViewFragment.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/MainActivity.java
- Clean the useless code on the mainActivtity
- Add test for the logout
> Dahn MainActivity clean code + Logout test

- app/src/main/java/ch/epfl/sweng/zuluzulu/Adapters/ChannelArrayAdapter.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Structure/Channel.java
- app/src/main/res/drawable/channel_background.xml
- app/src/main/res/layout/channel.xml
- app/src/main/res/layout/fragment_channel.xml
Related issue : #126 
- The channels can now have wonderful icons.
<p align="center">
</p>
> More beautiful channels

- app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/ChannelFragment.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/LoginFragment.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/MainFragment.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/MainActivity.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Structure/GPS.java
Related to the issue: #128 
- The GPS is started when the user is logged in.
- The GPS is stopped when the user is logged out.
This increases the window of time that the GPS works, hence we have more precision.
- Location updates are requested less frequently.
This decreases the battery demand without significantly decreasing the precision.
> The GPS is more precise

- app/src/androidTest/java/ch/epfl/sweng/zuluzulu/ChannelFragmentTest.java
- app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Structure/GPSTest.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/ChannelFragment.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/ChatFragment.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Structure/GPS.java
- app/src/main/res/layout/fragment_channel.xml
Related to issue: #125 
- The user can swipe up to reload the list of the available channels.
I still need to add tests.
> Refresh channels

- app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/ChannelFragment.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/MainActivity.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Structure/GPS.java
Now the GPS works correctly when you leave the app and come back.
- When you leave, it stops the GPS, in any case.
- When you come back, it checks if you are connected. If you are, then it starts the GPS. (So now, when the app says that you must activate your GPS to have access to all features, you can leave, go to the settings, activate the GPS, get back and the app knows that the GPS has been activated.)
> Better GPS

- app/src/androidTest/java/ch/epfl/sweng/zuluzulu/ChatFragmentTest.java
- app/src/androidTest/java/ch/epfl/sweng/zuluzulu/SettingsFragmentTest.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Adapters/ChatMessageArrayAdapter.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/ChatFragment.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/SettingsFragment.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Structure/ChatMessage.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Structure/GPS.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Structure/User.java
- app/src/main/res/layout/chat_message_noname.xml
- app/src/main/res/layout/fragment_chat.xml
- app/src/main/res/layout/fragment_settings.xml
- app/src/main/res/values/strings.xml
Related issue : #149 
- The user can go to the settings to be anonymous when he writes in the chats. The anonymity is stored in the preferences of the phone.
- Added a few tests.
> Anonymous chat

- app/src/androidTest/java/ch/epfl/sweng/zuluzulu/MementoFragmentTest.java
- app/src/androidTest/java/ch/epfl/sweng/zuluzulu/TestingUtility/TestWithUserAndFragment.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/CommunicationTag.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/AddEventFragment.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/AssociationDetailFragment.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/AssociationFragment.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/AssociationsGeneratorFragment.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/CalendarFragment.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/ChannelFragment.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/IdlingResource/IdlingResourceFactory.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/MainActivity.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/MementoFragment.java
- app/src/main/res/layout/fragment_memento.xml
Now use IdlingResourceFactory instead of sending message to the MainActivity
> Better IdlingResource

- app/src/androidTest/java/ch/epfl/sweng/zuluzulu/EventDetailFragmentTest.java
- app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Fragments/EventFragmentTest.java
- app/src/androidTest/java/ch/epfl/sweng/zuluzulu/MementoFragmentTest.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/MementoFragment.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Structure/Event.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Structure/EventDate.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/URLTools/MementoParser.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/URLTools/UrlHandler.java
- app/src/test/java/ch/epfl/sweng/zuluzulu/EventTest.java
- app/src/test/java/ch/epfl/sweng/zuluzulu/Structure/EventDateTest.java
We can now add all events from the memento to the database
New event fields :
- website
- contact
- url_place_and_room
- category
- speaker
- end_date
New class : EventDate for an event
@lbarras27 @yanngabbud @Ikaras998
> Load all events from memento and add to database #214

- app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/MementoFragment.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Structure/Event.java
- app/src/test/java/ch/epfl/sweng/zuluzulu/EventTest.java
Add tests
Add tests to the event class
#214 
Better code coverage
> Add event tests#214

- app/src/androidTest/java/ch/epfl/sweng/zuluzulu/EventDetailFragmentTest.java
- app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Fragments/ChannelFragmentTest.java
- app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Fragments/PostFragmentTest.java
- app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Fragments/ReplyFragmentTest.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Adapters/PostArrayAdapter.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/EventFragment.java
New tests on list view items
I added some tests for the list view items. Some of them are still in comment because we need to mock firebase completly before.
No related issue
Increase the code coverage
I don't test tests
> Add tests on some list view items

- app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Database/MockedProxy.java
- app/src/androidTest/java/ch/epfl/sweng/zuluzulu/LocalDatabase/UserDatabaseTest.java
- app/src/androidTest/java/ch/epfl/sweng/zuluzulu/TestWithAdmin.java
- app/src/androidTest/java/ch/epfl/sweng/zuluzulu/TestWithAuthenticatedUser.java
- app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Utility.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/MainFragment.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/LocalDatabase/UserDatabase.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/LocalDatabase/UserDatabaseContract.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/LocalDatabase/UserDatabaseHelper.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/MainActivity.java
- app/src/test/java/ch/epfl/sweng/zuluzulu/AuthenticatedUserTest.java
- app/src/test/java/ch/epfl/sweng/zuluzulu/TestingUtility/Utility.java
- app/src/test/java/ch/epfl/sweng/zuluzulu/UserTest.java
The user is now saved to a local SQLite database
#266
> Dahn save USER in SQL DATABASE 

- app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Database/MockedProxy.java
- app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Fragments/ChatFragmentTest.java
- app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Fragments/PostFragmentTest.java
- app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Fragments/ReplyFragmentTest.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Adapters/ChatMessageArrayAdapter.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/ChatFragment.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/SuperChatPostsFragment.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Structure/SuperMessage.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Utility/PostColor.java
- app/src/main/res/layout/chat_message.xml
Each message displays his time.
- The user can see when each message has been written, but only the same day.
- Fix for the wrong chat sorting.
#272 
Could be useful for the users.
> Chat message time

- app/build.gradle
- app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Database/CollectionAdapterTest.java
- app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Database/CollectionMock.java
- app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Database/DocumentMock.java
- app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Database/TaskMock.java
- app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Firebase/Database/DocumentAdapterTest.java
- app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Firebase/FirebaseProxyTest.java
- app/src/androidTest/java/ch/epfl/sweng/zuluzulu/URLTools/UrlHandlerTest.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Adapters/AddAssociationAdapter.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Firebase/Database/CollectionAdapter.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Firebase/Database/DatabaseCollection.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Firebase/Database/DatabaseDocument.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Firebase/Database/DocumentAdapter.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Firebase/Database/OperationWithFirebaseMap.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Firebase/Database/OperationWithFirebaseMapList.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Firebase/FirebaseMapDecorator.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Firebase/FirebaseProxy.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/ChannelFragment.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/LocalDatabase/UserDatabaseContract.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/MainActivity.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Structure/EventDate.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Structure/GPS.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Utility/Utils.java
- app/src/test/java/ch/epfl/sweng/zuluzulu/AuthServerTest.java
mock the proxy and add tests
#283
> Dahn tests - Mock proxy

- app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Fragments/AddEventFragmentTest.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Firebase/FirebaseProxy.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/AdminFragments/AddEventFragment.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/LoginFragment.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/ProfileFragment.java
- app/src/main/java/ch/epfl/sweng/zuluzulu/Utility/BitmapUtils.java
cleaning and adding comments
cleaning the code, adding comments, removing useless statements
> added comments for the proxy, cleaned addEvent, Profile and Login code
